// src/components/elements/Header.vue
<template>
	<header>
		<div class="container">
			<div class="logo">
				<router-link to="/">
					<img src="../../assets/images/logo.svg" alt="logo">
				</router-link>
			</div>
			<nav>
				<ul class="nav-menu">
					<li>
						<div class="promotion">
							<p>on sale</p>
						</div>
						<router-link to="/">
							web hosting
						</router-link>
					</li>
					<li>
						<router-link to="/">
							cloud hosting
						</router-link>
					</li>
					<li>
						<router-link to="/">
							vps hosting
						</router-link>
					</li>
					<li>
						<router-link to="/">
							domain checker
						</router-link>
					</li>
					<li>
						<router-link to="/">
							website builder
						</router-link>
					</li>
				</ul>
			</nav>

		</div>
	</header>

</template>

<script>
	export default {
		name: "Header"
	}
</script>

<style scoped lang="scss">
	.logo {
		display: inline-block;
	}

	li {
		a {
			color: $white;
			text-decoration: none;
			text-transform: uppercase;
		}
	}

	nav {
		float: right;
	}

</style>

// src/app/header/header.component.ts
import { Component, OnInit } from "@angular/core";

@Component({
  selector: "app-header",
  templateUrl: "./header.component.html",
  styleUrls: ["./header.component.scss"]
})
export class HeaderComponent implements OnInit {
  HostingerLogo = "../assets/images/logo.png";
  
  constructor() {
    

  }

  ngOnInit() {}
}

<header class="toolbar">
  
  <nav class="container">
    <div class="toolbar__toggle-button">
        <app-burger-button></app-burger-button>
      </div>
      
      <div class="toolbar__logo">
    
      <a href="#" class="toolbar__logo-brand"
        ><img [src]="HostingerLogo" alt="Hostinger Logo"
      /></a>
    </div>

    <div class="toolbar__navigation-items">
      <ul>
        <li><a href="#">Web Hosting</a></li>
        <li>
          <a href="#"><span>on sale</span>Cloud Hosting</a>
        </li>
        <li><a href="#">Vps Hosting</a></li>
        <li><a href="#">Domain Checker</a></li>
        <li><a href="#">Website Builder</a></li>
      </ul>
    </div>
  </nav>
</header>
