// src/components/Footer/Footer.jsx
import React from 'react';

class Footer extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      footerItems: [
        'Guaranteed 99.9% Uptime',
        'Superior Speed Performance',
        '24/7 Support Chat',
        '30-Day Money-Back Guarantee'
      ]
    }
  }

  renderFooterItems() {
    return this.state.footerItems.map((item, index) => (
        <div key={ index } className="footer-item">
          <span className="footer-icon icon"></span>
          <span className="footer-text"> { item } </span>
        </div>
    ));
  }

  /* 
  Let's imagine that footer items are coming from backend
  and we saved them in component's state.
  */
  render() {
    return !!this.state.footerItems.length &&(
      <div className="footer">
        { this.renderFooterItems() }
      </div>
    );
  }
}

export default Footer;

// src/components/offer/footer.vue
<template>
  <div id="offer-footer">
    <div class="d-flex flex-column flex-sm-row justify-content-between mb-3">
      <div v-for="(feature, index) in features" :key="index" class="offer-feature py-2">
        <font-awesome-icon icon="check"/> {{feature}}
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data: function () {
    return {
      features: [
        'Guaranteed 99.9% uptime',
        'Superior speed performance',
        '24/7 support chat',
        '30-Day Money-Back guarantee'
      ]
    }
  }
}
</script>

<style lang="scss" scoped>
#offer-footer {
  @media (min-width: 991px) {
      margin: 0 -15px !important;
    }
  .offer-feature {
    font-size: 18px;
    text-transform: capitalize;

    @media (min-width: 991px) {
      padding: 0 15px !important;
    }
    @media (max-width: 576px) {
      padding: 0 0 !important;
    }
    svg {
      font-size: 15px;
      margin-right: 4px;
      color: $green-light;
    }
  }
}
</style>
